### PR TITLE
Pre beta

### PR DESCRIPTION
**Pull request by skn3**
ahhhhh there we go :D figured it out .. click the black boxes and I can choose which I am asking you to merge with.. sorry if you just got totally spammed with notifications!

### CODE REVIEW

**Comment by devolonter** [comment]
Don't worry! Thanks again! :)

**Comment by skn3** [comment]
hurrah cool figured it :).. I got confused because I thought it would carry over the branch I currently had selected when clicking to fork and edit the file.

**Comment by devolonter** [comment]
Your way of creation separate branch (patch-1) for fixing was correct. Fork and edit the file is a good feature if you change a few lines, but if there are a lot of changes that will bring you a headache.
I was glad to see that you've joined this project. Any help is very much appreciated :) Also, you can ask me questions about git or github. I'll try to help!

**Comment by skn3** [comment]
Hey Arthur,

Cool thanks for the confirmation on git stuff. I have only really used 
the very basics of git working on my projects alone, so its interesting 
to delve into the more collaborative bits! I will be using the flixel 
port with some friends to complete teh Saucy hater game, so will try 
and contribute fixes if we spot any!

Is there stuff in flixel that simply isnt possible in monkey, or is it 
all portable?

**Pull request merged**
